name: wechat
description: A Chatting Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # For Animation
  simple_animations: ^5.0.2
  page_transition: ^2.1.0

  # Google Fonts To use over 900+ fonts from fonts.google.com
  google_fonts: ^6.1.0

  # Riv animation in Splash Screen
  rive: ^0.12.2
  lottie: ^2.7.0

  # Firebase Plugins
  firebase_core: ^2.21.0 # For integration App to FireBase
  firebase_auth: ^4.12.1 # For Handling Firebase Authentication
  cloud_firestore: ^4.14.0 # For data base integration

  # Google Sign-In Plugins
  google_sign_in: ^6.1.5 # For handling Google Sign In

  # Mark Down for Privacy and Term and Condition Policy
  flutter_markdown: ^0.6.18+3

  # For navigating markdown to A website
  url_launcher: ^6.2.3

  # Successfully Sign in Snack Bar
  awesome_snackbar_content: ^0.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - animation/
    - termandcond/

